# Generated by Django 3.0.8 on 2020-09-20 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AboutBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('extra_text_en', models.TextField(blank=True, null=True)),
                ('name_uz', models.CharField(max_length=100)),
                ('extra_text_uz', models.TextField(blank=True, null=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_box', to='cubic.About')),
                ('saved', models.ManyToManyField(blank=True, related_name='saved_about_box', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cubes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('text_en', models.TextField(blank=True, null=True)),
                ('congra_text_en', models.TextField(blank=True, null=True)),
                ('name_uz', models.CharField(max_length=100)),
                ('text_uz', models.TextField(blank=True, null=True)),
                ('congra_text_uz', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RubicsCubeProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='rubics_cube')),
                ('img2', models.ImageField(upload_to='rubics_cube')),
                ('img3', models.ImageField(upload_to='rubics_cube')),
                ('img4', models.ImageField(upload_to='rubics_cube')),
                ('img5', models.ImageField(upload_to='rubics_cube')),
                ('img6', models.ImageField(upload_to='rubics_cube')),
                ('img7', models.ImageField(upload_to='rubics_cube')),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name_en', models.CharField(max_length=100)),
                ('step_name_uz', models.CharField(max_length=100)),
                ('cube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='cubic.Cubes')),
            ],
        ),
        migrations.CreateModel(
            name='StepsStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name_en', models.CharField(max_length=100)),
                ('step_name_uz', models.CharField(max_length=100)),
                ('extra_text_en', models.TextField(blank=True, null=True)),
                ('main_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step', to='cubic.Steps')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='cubes/solution')),
                ('solution', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('extra_text_en', models.TextField(blank=True, null=True)),
                ('name_uz', models.CharField(max_length=100)),
                ('extra_text_uz', models.TextField(blank=True, null=True)),
                ('saved', models.ManyToManyField(blank=True, related_name='saved_solution_card', to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cubic.StepsStep')),
            ],
        ),
        migrations.CreateModel(
            name='AboutCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='cubes/about')),
                ('name_en', models.CharField(max_length=100)),
                ('extra_text_en', models.TextField(blank=True, null=True)),
                ('name_uz', models.CharField(max_length=100)),
                ('extra_text_uz', models.TextField(blank=True, null=True)),
                ('about_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_cards', to='cubic.AboutBox')),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='cube',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about', to='cubic.Cubes'),
        ),
    ]
