# Generated by Django 3.0.8 on 2020-09-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepsstep',
            name='extra_text_uz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
