# Generated by Django 3.0.8 on 2020-09-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubic', '0002_stepsstep_extra_text_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='solution_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
