# Generated by Django 3.0.8 on 2020-09-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubic', '0003_card_solution_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='congra_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='steps',
            name='congra_text_uz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
