# Generated by Django 3.0.8 on 2020-09-21 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cubic', '0006_aboutbox_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartsOfCube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='rubics_cube/parts_of_cube')),
                ('name_en', models.CharField(max_length=100)),
                ('extra_text_en', models.TextField(blank=True, null=True)),
                ('name_uz', models.CharField(max_length=100)),
                ('extra_text_uz', models.TextField(blank=True, null=True)),
                ('cube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_of_cube', to='cubic.Cubes')),
            ],
        ),
    ]
