# Generated by Django 3.0.8 on 2020-09-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubic', '0008_diarynote_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PyramidProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='pyramid')),
                ('img2', models.ImageField(upload_to='pyramid')),
                ('img3', models.ImageField(upload_to='pyramid')),
                ('img4', models.ImageField(upload_to='pyramid')),
                ('img5', models.ImageField(upload_to='pyramid')),
            ],
        ),
    ]
