# Generated by Django 3.0.8 on 2020-09-26 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cubic', '0009_pyramidprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='cube',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cubic.Cubes'),
            preserve_default=False,
        ),
    ]
